#!/usr/bin/env bash
# transfers a file from a client to a server with scp

SCRIPT_NAME="$0"
FILE_PATH="$1"
IP_ADDRESS="$2"
USERNAME="$3"
SSH_PRIVATE_PATH="$4"

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_PATH" "$FILE_PATH" "$USERNAME"@"$IP_ADDRESS":~/

if [ $? -eq 0 ]; then
	echo "Transfer successful"
else
	echo "Transfer failed"
fi
