#!/usr/bin/env bash
# Variables for backend server addresses
BACKEND_SERVER_1="289100-web-01"
BACKEND_SERVER_1_IP="54.157.160.208"
BACKEND_SERVER_2="289100-web-02"
BACKEND_SERVER_2_IP="54.160.121.210"

# Install HAProxy (version 2.4)
sudo apt-get update -y
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update -y
sudo apt-get install -y haproxy=2.4.*

# Create a backup of the HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    mode http
    log global
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend localnodes
    bind *:80
    mode http
    default_backend nodes

backend nodes
    mode http
    balance roundrobin
    server 289100-web-01 54.157.160.208
    server 289100-web-02 54.160.121.210
EOF

# Make HAProxy manageable via an init script
sudo systemctl enable haproxy

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
