#!/bin/bash

# Update package lists
sudo apt-get -y update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
server_config=\
"
frontend http_front
        bind *:80
	mode http
	default_backend http_back

backend http_back
	balance roundrobin
	server 289100-web-01 54.157.160.208:80 check
	server 289100-web-02 54.160.121.210:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
