#!/usr/bin/env bash
# Prints "Best School" 10 times and "Hi"on the 9th iteration

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
