#!/usr/bin/env bash
# Loops from 1 to 10 and prints:
#   "bad luck" on the 4th iteration,
#   "good luck" on the 8th iteration,
#   then "Holberton School" otherwise

n=0

while [ $n -lt 10 ]
do
  if [ $n -eq 3 ]
  then
    echo "bad luck"
  elif [ $n -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( n++ ))
done
