#!/usr/bin/env bash
# Prints 1 to 20 with-:
#   "bad luck from China" on the 4th iteration
#   "bad luck from Japan" on the 9th iteration
#   "bad luck from Italy" on the 17th loop iteration

iter=1

while [ $iter -le 20 ]
do
  echo "$iter"
  case $iter in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( iter++ ))
done
